
// src/styles/myRankingStyles.js

import { StyleSheet } from 'react-native';
import { authTheme } from './authTheme';

export const myRankingStyles = StyleSheet.create({
  myRankingScrollContent: {
    paddingBottom: 120,
  },
  myHeroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 18,
    marginBottom: 14,
    ...authTheme.shadow.soft,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: authTheme.colors.brandMint,
    borderColor: '#BBF7D0',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  heroBadgeText: {
    color: authTheme.colors.brandTeal,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  myHeroTitle: {
    color: authTheme.colors.gray900,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  myHeroText: {
    marginTop: 6,
    color: authTheme.colors.brandMuted,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '600',
  },
  controlCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 16,
    marginBottom: 14,
    ...authTheme.shadow.soft,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 14,
  },
  sectionTitleRowCompact: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingRight: 8,
  },
  collapsibleTitleBlock: {
    flex: 1,
    paddingRight: 4,
  },
  titleWithInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    flexWrap: 'wrap',
  },
  infoMiniButton: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  sectionTitle: {
    color: authTheme.colors.gray900,
    fontSize: 16,
    fontWeight: '900',
  },
  sectionSubtitle: {
    marginTop: 2,
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  hideShowBtn: {
    minWidth: 78,
    minHeight: 36,
    borderRadius: 14,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  hideShowText: {
    color: authTheme.colors.brandTeal,
    fontSize: 11,
    fontWeight: '900',
  },
  collapsibleBody: {
    marginTop: 14,
  },
  inlineErrorBox: {
    marginTop: 12,
    borderRadius: 16,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 7,
  },
  inlineErrorText: {
    flex: 1,
    color: '#B91C1C',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  importanceGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  importanceBox: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
  },
  importanceLabel: {
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '900',
  },
  importanceValue: {
    color: authTheme.colors.brandTeal,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  hintText: {
    marginTop: 9,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 18,
    padding: 12,
    marginBottom: 14,
  },
  warningNotice: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
  },
  noticeText: {
    flex: 1,
    color: authTheme.colors.brandTeal,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  warningText: {
    color: '#B45309',
  },
  weightCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: 12,
    marginBottom: 12,
  },
  weightHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  weightTitle: {
    color: authTheme.colors.gray900,
    fontSize: 13,
    fontWeight: '900',
  },
  weightHelper: {
    marginTop: 3,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  weightValueBox: {
    minWidth: 58,
    height: 38,
    borderRadius: 14,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weightValue: {
    color: authTheme.colors.brandTeal,
    fontSize: 14,
    fontWeight: '900',
  },
  removeBtn: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sliderRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weightSlider: {
    flex: 1,
    height: 38,
  },
  sliderSideText: {
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '900',
  },
  sliderHintText: {
    marginTop: 6,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  addBox: {
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
  },
  addLabel: {
    color: authTheme.colors.gray700,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  addRow: {
    flexDirection: 'row',
    gap: 8,
  },
  selectBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  disabledSelect: {
    opacity: 0.55,
  },
  selectText: {
    flex: 1,
    color: authTheme.colors.gray900,
    fontSize: 12,
    fontWeight: '800',
  },
  disabledText: {
    color: authTheme.colors.gray500,
  },
  addBtn: {
    width: 70,
    borderRadius: 14,
    backgroundColor: authTheme.colors.brandTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnDisabled: {
    opacity: 0.5,
  },
  addBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  actionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 14,
    marginBottom: 14,
    ...authTheme.shadow.soft,
  },
  primaryAction: {
    height: 48,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 10,
  },
  disabledAction: {
    opacity: 0.55,
  },
  actionGradient: {
    flex: 1,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryActionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  smallAction: {
    flexGrow: 1,
    flexBasis: 130,
    minHeight: 42,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  smallActionDisabled: {
    opacity: 0.45,
  },
  smallActionText: {
    color: authTheme.colors.brandTeal,
    fontSize: 12,
    fontWeight: '900',
  },
  smallActionTextDisabled: {
    color: authTheme.colors.gray500,
  },
  successMessage: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: authTheme.colors.brandTeal,
    fontSize: 12,
    fontWeight: '800',
  },
  errorBox: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    borderRadius: 18,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    padding: 12,
    marginBottom: 14,
  },
  errorText: {
    flex: 1,
    color: '#B91C1C',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  resultsHeaderCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    ...authTheme.shadow.soft,
  },
  resultsTitle: {
    color: authTheme.colors.gray900,
    fontSize: 17,
    fontWeight: '900',
  },
  resultsSub: {
    marginTop: 2,
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  exportPageBtn: {
    minHeight: 36,
    borderRadius: 13,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  exportPageText: {
    color: authTheme.colors.brandTeal,
    fontSize: 11,
    fontWeight: '900',
  },
  emptyMyBox: {
    borderRadius: 24,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    padding: 22,
    alignItems: 'center',
    marginBottom: 14,
  },
  emptyMyTitle: {
    marginTop: 8,
    color: authTheme.colors.brandTeal,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyMyText: {
    marginTop: 4,
    textAlign: 'center',
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  resultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 14,
    marginBottom: 14,
    ...authTheme.shadow.soft,
  },
  resultTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
  },
  rankBadge: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankBadgeLabel: {
    color: authTheme.colors.brandTeal,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  rankBadgeValue: {
    color: authTheme.colors.brandTeal,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  resultTitleBox: {
    flex: 1,
    paddingTop: 2,
  },
  resultName: {
    color: authTheme.colors.gray900,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 20,
  },
  resultCountry: {
    marginTop: 4,
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  scorePills: {
    marginTop: 13,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  scorePill: {
    borderRadius: 999,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  scorePillLabel: {
    color: authTheme.colors.brandMuted,
    fontSize: 10,
    fontWeight: '900',
  },
  scorePillValue: {
    color: authTheme.colors.brandTeal,
    fontSize: 11,
    fontWeight: '900',
  },
  explanationBox: {
    marginTop: 12,
    gap: 7,
  },
  reasonChip: {
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  reasonText: {
    flex: 1,
    color: authTheme.colors.gray700,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 13,
    alignItems: 'center',
  },
  iconActionBtn: {
    width: 40,
    height: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareIconActive: {
    backgroundColor: authTheme.colors.brandTeal,
    borderColor: authTheme.colors.brandTeal,
  },
  saveIconActive: {
    backgroundColor: '#F59E0B',
    borderColor: '#F59E0B',
  },
  breakdownBtn: {
    flex: 1,
    height: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    backgroundColor: authTheme.colors.brandMint,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  breakdownBtnText: {
    color: authTheme.colors.brandTeal,
    fontSize: 11,
    fontWeight: '900',
  },
  breakdownWrap: {
    marginTop: 13,
    gap: 10,
  },
  breakdownCard: {
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
  },
  breakdownTitle: {
    color: authTheme.colors.gray900,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  noBreakdownText: {
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  breakdownRow: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingVertical: 9,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  breakdownLabel: {
    color: authTheme.colors.gray700,
    fontSize: 12,
    fontWeight: '800',
  },
  breakdownMeta: {
    marginTop: 2,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  breakdownContribution: {
    color: authTheme.colors.brandTeal,
    fontSize: 12,
    fontWeight: '900',
  },
  myPagination: {
    marginTop: 2,
    marginBottom: 18,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  myPageBtn: {
    borderRadius: 14,
    backgroundColor: authTheme.colors.brandTeal,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  myPageDisabled: {
    opacity: 0.45,
  },
  myPageBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  myPageText: {
    color: authTheme.colors.gray700,
    fontSize: 12,
    fontWeight: '900',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.52)',
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceCard: {
    width: '100%',
    maxWidth: 480,
    maxHeight: '78%',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 16,
  },
  saveNameCard: {
    width: '100%',
    maxWidth: 480,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 16,
  },
  savedModalCard: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '82%',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 16,
  },
  infoModalCard: {
    width: '100%',
    maxWidth: 480,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 16,
    ...authTheme.shadow.soft,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
  modalMiniLabel: {
    color: authTheme.colors.brandTeal,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modalTitle: {
    color: authTheme.colors.gray900,
    fontSize: 18,
    fontWeight: '900',
    flexShrink: 1,
  },
  modalHelper: {
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginBottom: 12,
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 13,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceItem: {
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    marginBottom: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  choiceLabel: {
    color: authTheme.colors.gray900,
    fontSize: 13,
    fontWeight: '900',
  },
  choiceHelper: {
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  nameInput: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 13,
    color: authTheme.colors.gray900,
    fontSize: 14,
    fontWeight: '800',
  },
  modalActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  modalCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: {
    color: authTheme.colors.gray700,
    fontSize: 13,
    fontWeight: '900',
  },
  modalSaveBtn: {
    flex: 1,
    height: 44,
    borderRadius: 15,
    backgroundColor: authTheme.colors.brandTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  noSavedBox: {
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    padding: 22,
  },
  noSavedTitle: {
    marginTop: 8,
    color: authTheme.colors.brandTeal,
    fontSize: 15,
    fontWeight: '900',
  },
  noSavedText: {
    marginTop: 4,
    textAlign: 'center',
    color: authTheme.colors.brandMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  savedRankingCard: {
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    padding: 12,
    marginBottom: 10,
  },
  savedRankingTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  savedRankingName: {
    color: authTheme.colors.gray900,
    fontSize: 14,
    fontWeight: '900',
  },
  savedRankingMeta: {
    marginTop: 4,
    color: authTheme.colors.brandTeal,
    fontSize: 12,
    fontWeight: '800',
  },
  savedRankingDate: {
    marginTop: 3,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  datasetPill: {
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  datasetPillText: {
    color: authTheme.colors.brandTeal,
    fontSize: 10,
    fontWeight: '900',
  },
  previewText: {
    marginTop: 9,
    color: authTheme.colors.brandMuted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  savedRankingActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  applyBtn: {
    flex: 1,
    height: 40,
    borderRadius: 14,
    backgroundColor: authTheme.colors.brandTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  deleteBtn: {
    flex: 1,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  deleteBtnText: {
    color: '#DC2626',
    fontSize: 12,
    fontWeight: '900',
  },
  infoTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  infoModalIcon: {
    width: 40,
    height: 40,
    borderRadius: 16,
    backgroundColor: authTheme.colors.brandMint,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoBodyText: {
    color: authTheme.colors.gray700,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 12,
  },
  infoPointsBox: {
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    gap: 9,
  },
  infoPointRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  infoPointText: {
    flex: 1,
    color: authTheme.colors.gray700,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  infoGotItBtn: {
    marginTop: 14,
    height: 44,
    borderRadius: 15,
    backgroundColor: authTheme.colors.brandTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoGotItText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
});