// src/styles/researcherStyles.js
//
// Styles for the Researcher screens. Built from the same authTheme tokens and
// card / pill / input measurements as dashboardStyles and rankingsStyles, so
// the researcher area looks like the rest of the app.

import { StyleSheet, Platform } from 'react-native';
import { authTheme, CONTENT_MAX_WIDTH } from './authTheme';

const colors = authTheme.colors;

const INPUT_BG = '#F3F6FA';
const INPUT_BORDER = '#D7DDE5';
const SOFT_WHITE = '#F8FFFC';

const center = { alignItems: 'center', justifyContent: 'center' };
const cardBorder = { borderWidth: 1, borderColor: colors.brandBorder };
const cardShadow = {
  shadowColor: '#94A3B8',
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.13,
  shadowRadius: 14,
  elevation: 4,
};
const uppercaseLabel = { fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1 };

export const researcherStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.brandMint },
  scroll: { flex: 1, backgroundColor: colors.brandMint },
  // Content is capped and centred on wide screens (tablets, foldables) so
  // cards do not stretch edge to edge.
  content: {
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 32,
  },

  // ── Top bar ────────────────────────────────────────────────────────────
  // paddingTop is added at runtime from the device's safe-area inset.
  topBar: {
    paddingTop: 10,
    paddingHorizontal: 12,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F766E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
    zIndex: 10,
  },
  topButton: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.16)',
    ...center,
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', flex: 1, marginLeft: 10 },
  navLogoWrap: {
    width: 34,
    height: 34,
    borderRadius: 13,
    backgroundColor: colors.brandMintDeep,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    marginRight: 8,
    ...center,
  },
  navLogo: { width: 28, height: 28 },
  navBrand: { fontSize: 18, lineHeight: 22, fontWeight: '900', color: '#FFFFFF', letterSpacing: -0.3 },
  navRole: { fontSize: 9.5, fontWeight: '800', color: 'rgba(255,255,255,0.85)', letterSpacing: 0.6 },

  // ── Page header / cards ────────────────────────────────────────────────
  heroCard: {
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingTop: 13,
    paddingBottom: 14,
    marginBottom: 12,
    backgroundColor: colors.whiteSoft,
    ...cardBorder,
    ...cardShadow,
  },
  badge: {
    alignSelf: 'flex-start',
    minHeight: 28,
    borderRadius: 999,
    backgroundColor: SOFT_WHITE,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    marginBottom: 8,
    ...cardBorder,
  },
  badgeDot: { width: 7, height: 7, borderRadius: 999, backgroundColor: colors.brandGreen, marginRight: 7 },
  badgeText: { fontSize: 10, lineHeight: 13, color: colors.brandTeal, ...uppercaseLabel },
  heroTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    color: colors.gray900,
    letterSpacing: -0.4,
    marginBottom: 5,
  },
  heroSubtitle: { fontSize: 12, lineHeight: 18, color: colors.brandMuted },

  card: {
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingTop: 12,
    paddingBottom: 13,
    marginBottom: 12,
    backgroundColor: colors.whiteSoft,
    ...cardBorder,
    shadowColor: '#94A3B8',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.11,
    shadowRadius: 12,
    elevation: 3,
  },
  eyebrow: { fontSize: 10, lineHeight: 13, color: colors.brandTeal, marginBottom: 2, ...uppercaseLabel },
  sectionTitle: { fontSize: 15.5, lineHeight: 20, fontWeight: '900', color: colors.gray900, marginBottom: 2 },
  sectionSubtitle: { fontSize: 11.5, lineHeight: 17, color: colors.brandMuted, marginBottom: 8 },
  bodyText: { fontSize: 12.5, lineHeight: 19, color: colors.gray700 },
  mutedText: { fontSize: 11.5, lineHeight: 17, color: colors.brandMuted },
  noteText: { fontSize: 10.5, lineHeight: 16, color: '#94A3B8', marginTop: 8 },
  boldText: { fontWeight: '900', color: colors.gray900 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },

  // ── Inputs ─────────────────────────────────────────────────────────────
  label: { fontSize: 10, lineHeight: 13, color: colors.brandTeal, marginBottom: 5, ...uppercaseLabel },
  searchBox: {
    minHeight: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    backgroundColor: INPUT_BG,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  searchIcon: { fontSize: 15, color: colors.brandTeal, marginRight: 7 },
  searchInput: {
    flex: 1,
    minHeight: 40,
    fontSize: 13,
    color: colors.gray900,
    fontWeight: '500',
    paddingVertical: Platform.OS === 'ios' ? 7 : 4,
  },
  clearText: { color: colors.brandMuted, fontSize: 13, fontWeight: '900', paddingLeft: 8 },
  selectBox: {
    minHeight: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    backgroundColor: INPUT_BG,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectDisabled: { opacity: 0.55 },
  selectText: { flex: 1, fontSize: 13, lineHeight: 17, fontWeight: '700', color: colors.gray900 },
  selectArrow: { fontSize: 15, fontWeight: '900', color: colors.brandTeal, marginLeft: 6 },
  textArea: {
    minHeight: 64,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 11,
    paddingVertical: 9,
    fontSize: 13,
    color: colors.gray900,
    textAlignVertical: 'top',
  },
  textInput: {
    minHeight: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 11,
    fontSize: 13,
    color: colors.gray900,
  },
  inputError: { borderColor: '#F87171' },
  fieldGap: { marginBottom: 10 },
  twoCol: { flexDirection: 'row', gap: 8 },
  flex1: { flex: 1 },

  // ── Segmented / dataset switcher ───────────────────────────────────────
  segment: {
    flexDirection: 'row',
    borderRadius: 16,
    padding: 4,
    backgroundColor: '#FFFFFF',
    marginBottom: 10,
    ...cardBorder,
  },
  segmentItem: { flex: 1, minHeight: 38, borderRadius: 12, overflow: 'hidden' },
  segmentFill: { flex: 1, minHeight: 38, borderRadius: 12, paddingHorizontal: 6, paddingVertical: 6, ...center },
  segmentText: { fontSize: 12.5, fontWeight: '900', color: colors.brandMuted, textAlign: 'center' },
  segmentTextActive: { color: '#FFFFFF' },
  segmentHint: { fontSize: 9.5, fontWeight: '700', color: colors.brandMuted, marginTop: 1, textAlign: 'center' },
  segmentHintActive: { color: 'rgba(255,255,255,0.85)' },
  switcherRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },

  // ── Buttons ────────────────────────────────────────────────────────────
  gradientButtonOuter: { borderRadius: 14, overflow: 'hidden', ...authTheme.shadow.button },
  gradientButton: { minHeight: 44, paddingHorizontal: 16, ...center },
  gradientButtonSmall: { minHeight: 34, paddingHorizontal: 12 },
  gradientButtonText: { fontSize: 13, lineHeight: 17, fontWeight: '900', color: '#FFFFFF' },
  outlineButton: {
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1.2,
    borderColor: colors.brandTeal,
    backgroundColor: '#FFFFFF',
    ...center,
  },
  outlineButtonSmall: { minHeight: 32, paddingHorizontal: 10, borderRadius: 11, borderWidth: 1 },
  outlineButtonText: { fontSize: 13, fontWeight: '900', color: colors.brandTeal },
  dangerButton: { borderColor: '#FECACA', backgroundColor: '#FEF2F2' },
  dangerButtonText: { color: '#DC2626' },
  buttonDisabled: { opacity: 0.55 },
  buttonRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },

  // ── Stats / findings ───────────────────────────────────────────────────
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 8, marginBottom: 12 },
  statCard: {
    width: '48.5%',
    minHeight: 66,
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 9,
    backgroundColor: colors.whiteSoft,
    justifyContent: 'center',
    ...cardBorder,
  },
  statValue: { fontSize: 18, lineHeight: 22, fontWeight: '900', color: colors.brandTeal },
  statLabel: { fontSize: 10.5, lineHeight: 14, fontWeight: '800', color: colors.gray900, marginTop: 1 },
  statHint: { fontSize: 9.5, lineHeight: 13, color: colors.brandMuted, marginTop: 1 },
  finding: { borderRadius: 14, borderWidth: 1, padding: 10, marginBottom: 8 },
  findingTitle: { fontSize: 12.5, fontWeight: '900', color: colors.gray900, marginBottom: 3 },
  findingText: { fontSize: 12, lineHeight: 18, color: colors.brandMuted },

  // ── List rows ──────────────────────────────────────────────────────────
  rowCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.brandBorder,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginBottom: 8,
  },
  rowCardActive: { borderColor: colors.brandTeal, backgroundColor: SOFT_WHITE },
  rowTop: { flexDirection: 'row', alignItems: 'center' },
  rankPill: {
    minWidth: 46,
    height: 28,
    borderRadius: 10,
    paddingHorizontal: 7,
    backgroundColor: colors.brandMintDeep,
    marginRight: 10,
    ...cardBorder,
    ...center,
  },
  rankPillText: { fontSize: 11.5, fontWeight: '900', color: colors.brandTeal },
  rankPillTopText: { color: '#FFFFFF' },
  rowName: { fontSize: 13, lineHeight: 17, fontWeight: '900', color: colors.gray900 },
  rowSub: { fontSize: 11, lineHeight: 15, color: colors.brandMuted, marginTop: 1 },
  rowScoreBox: { alignItems: 'flex-end', marginLeft: 8 },
  rowScore: { fontSize: 13, fontWeight: '900', color: colors.brandTeal },
  rowScoreLabel: { fontSize: 9, fontWeight: '800', color: colors.brandMuted, textTransform: 'uppercase' },
  kvGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 9, rowGap: 6, columnGap: 6 },
  kvItem: {
    width: '48.8%',
    borderRadius: 11,
    backgroundColor: '#F3FBF8',
    borderWidth: 1,
    borderColor: '#DDF4EA',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  kvLabel: { fontSize: 9.5, lineHeight: 13, fontWeight: '800', color: colors.brandMuted },
  kvValue: { fontSize: 12, lineHeight: 16, fontWeight: '900', color: colors.gray900, marginTop: 1 },
  kvValueSub: { fontSize: 10, fontWeight: '800', color: colors.brandTeal, marginTop: 1 },
  expandText: { fontSize: 11, fontWeight: '900', color: colors.brandTeal, marginTop: 8 },

  // ── Badges ─────────────────────────────────────────────────────────────
  pill: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 3, alignSelf: 'flex-start' },
  pillText: { fontSize: 10.5, fontWeight: '900' },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.brandBorder,
    backgroundColor: SOFT_WHITE,
    paddingLeft: 11,
    paddingRight: 4,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 6,
    maxWidth: '100%',
  },
  chipText: { fontSize: 11.5, fontWeight: '900', color: colors.gray900, flexShrink: 1 },
  chipClose: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    marginLeft: 6,
    ...center,
  },
  chipCloseText: { color: '#DC2626', fontWeight: '900', fontSize: 14, marginTop: -1 },

  // ── States ─────────────────────────────────────────────────────────────
  emptyBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.brandBorder,
    backgroundColor: '#F3FBF8',
    paddingVertical: 26,
    paddingHorizontal: 14,
    ...center,
  },
  emptyText: { fontSize: 12.5, lineHeight: 18, fontWeight: '800', color: colors.gray900, textAlign: 'center' },
  loadingBox: { paddingVertical: 30, ...center },
  loadingText: { marginTop: 8, fontSize: 12, fontWeight: '700', color: colors.brandMuted, textAlign: 'center' },
  errorBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    padding: 11,
    marginBottom: 10,
  },
  errorText: { fontSize: 12, lineHeight: 17, fontWeight: '700', color: '#B91C1C' },
  warningBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FDE68A',
    backgroundColor: '#FFFBEB',
    padding: 11,
    marginBottom: 10,
  },
  warningText: { fontSize: 12, lineHeight: 17, fontWeight: '700', color: '#92400E' },
  successText: { fontSize: 11.5, fontWeight: '800', color: '#047857', textAlign: 'center', marginTop: 8 },

  // ── Pagination ─────────────────────────────────────────────────────────
  pagination: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 6 },
  pageButton: {
    minWidth: 38,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.brandBorder,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    ...center,
  },
  pageButtonText: { fontSize: 12.5, fontWeight: '900', color: colors.brandTeal },
  pageInfo: { fontSize: 12, fontWeight: '800', color: colors.gray700, minWidth: 64, textAlign: 'center' },

  // ── Bars ───────────────────────────────────────────────────────────────
  barTrack: { height: 7, borderRadius: 999, backgroundColor: '#E2E8F0', overflow: 'hidden' },
  barFill: { height: 7, borderRadius: 999, backgroundColor: colors.brandTeal },

  // ── Suggestions dropdown ───────────────────────────────────────────────
  suggestionBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.brandBorder,
    backgroundColor: '#FFFFFF',
    marginTop: -4,
    marginBottom: 10,
    overflow: 'hidden',
  },
  suggestionRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  suggestionName: { flex: 1, fontSize: 12.5, fontWeight: '800', color: colors.gray900 },
  suggestionMeta: { fontSize: 11, fontWeight: '800', color: colors.brandTeal, marginLeft: 8 },
  suggestionSub: { fontSize: 10.5, color: colors.brandMuted, marginTop: 1 },

  // ── Simple table (report) ──────────────────────────────────────────────
  table: { borderRadius: 12, borderWidth: 1, borderColor: colors.brandBorder, overflow: 'hidden' },
  tableRow: { flexDirection: 'row' },
  tableHeadCell: {
    backgroundColor: colors.brandMintDeep,
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: colors.brandBorder,
  },
  tableHeadText: { fontSize: 10, fontWeight: '900', color: colors.gray900, textTransform: 'uppercase' },
  tableCell: {
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: '#E8F3EE',
    borderRightWidth: 1,
    borderRightColor: '#E8F3EE',
    backgroundColor: '#FFFFFF',
  },
  tableCellText: { fontSize: 11.5, lineHeight: 16, color: colors.gray900 },

  // ── Menu ───────────────────────────────────────────────────────────────
  menuOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.32)', flexDirection: 'row' },
  menuPanel: {
    width: '82%',
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    // Top/bottom padding is added at runtime from the safe-area insets.
    paddingTop: 12,
    paddingBottom: 20,
    shadowColor: '#0F172A',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 4, height: 0 },
    elevation: 16,
  },
  menuHeader: { paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  menuGroupTitle: {
    fontSize: 10,
    color: colors.brandTeal,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 5,
    ...uppercaseLabel,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 2,
    paddingHorizontal: 9,
    paddingVertical: 8,
    borderRadius: 13,
  },
  menuItemActive: { backgroundColor: colors.brandMintDeep },
  menuIconBox: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#B7E9D4',
    marginRight: 10,
    ...center,
  },
  menuEmoji: { fontSize: 15 },
  menuLabel: { fontSize: 13, fontWeight: '800', color: colors.gray900 },
  menuLabelActive: { color: colors.brandTeal, fontWeight: '900' },
  menuHint: { fontSize: 10.5, fontWeight: '600', color: colors.brandMuted, marginTop: 1 },
  menuDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 8, marginHorizontal: 16 },
  logoutLabel: { fontSize: 13, fontWeight: '800', color: '#DC2626' },

  // ── Modal sheet ────────────────────────────────────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 18,
    borderWidth: 1,
    borderColor: '#BFE8D8',
  },
  modalTitle: { fontSize: 18, fontWeight: '900', color: colors.gray900, marginBottom: 4 },
});

export const researcherColors = {
  ...colors,
  amberBorder: '#FDE68A',
  amberBg: '#FFFBEB',
  amberText: '#B45309',
  orange: '#EA580C',
  red: '#DC2626',
  softMint: '#F3FBF8',
};
